---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: portfolio/works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: portfolio/tutoriaux
  label: Tutoriaux
  create: all
  match: "**/*"
  templates:
  - journal
- type: directory
  path: portfolio/journal
  label: Journal
  create: all
  match: "**/[!index]*"
  templates:
  - journal
- type: heading
  label: Theme settings
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
